name: ttnode
services:
  ttnode:
    image: registry.cn-hangzhou.aliyuncs.com/tiptime/ttnode:latest
    container_name: ttnode
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: host
    privileged: true
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /proc
        target: /host/proc
      - type: bind
        source: /DATA/AppData/ttnode
        target: /mnt/data/ttnode
    x-casaos:
      volumes:
        - container: /mnt/data/ttnode
          description:
            en_us: TTNODE data directory.
            zh_cn: TTNODE 数据目录
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: Cp0204
  category: Utilities
  description:
    en_us: TTNODE is a versatile platform that allows you to easily participate in various distributed computing projects. It supports a wide range of tasks and provides a user-friendly web interface for management.
    zh_cn: 甜糖星愿是一个多功能平台，可以轻松参与各种分布式计算项目。它支持广泛的任务，并提供了用户友好的Web界面进行管理。
  developer: ttnode
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/ttnode/icon.png
  tagline:
    en_us: Versatile distributed computing platform.
    zh_cn: 多功能分布式计算平台。
  tips:
    before_install:
      en_us: After installation, please be sure to change the mapping directory for `/DATA/AppData/ttnode`. This directory will cache a large number of CDN files.
      zh_cn: 安装后请务必更改 `/DATA/AppData/ttnode` 映射目录，该目录会大量缓存 CDN 文件。
  main: ttnode
  title:
    en_us: ttnode
    zh_cn: 甜糖
  index: /
  port_map: "1024"
  scheme: http