name: tailscaled
services:
  tailscaled:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TS_EXTRA_ARGS: --advertise-exit-node
      TS_ROUTES: 192.168.100.0/24
      TS_STATE_DIR: /var/lib/tailscale
    image: tailscale/tailscale:latest
    container_name: tailscaled
    deploy:
      resources:
        reservations:
          memory: "32M"
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /dev/net/tun
        target: /dev/net/tun
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /var/lib/tailscale
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: Cp0204
  category: VPN
  description:
    en_us: Tailscale is a zero config VPN for building secure networks. Install on any device in minutes. Remote access from any network or physical location.
    zh_cn: Tailscale 是一款用于构建安全网络的零配置 VPN。只需几分钟即可在任何设备上安装，即可从任何网络或物理位置远程访问。
  developer: tailscale
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/Tailscale/icon.png
  main: tailscaled
  tagline:
    en_us: A VPN Service for Secure Networks.
    zh_cn: 一个 VPN 服务，为安全网络提供保护。
  thumbnail:
  tips:
    before_install:
      en_us: After installation, view the authentication url in the `App Settings-Logs`.
      zh_cn: 安装完成后，请在`应用设置-日志`中查看认证链接。
  title:
    en_us: Tailscaled
