name: v2raya
services:
  v2raya:
    environment:
      V2RAYA_ADDRESS: 0.0.0.0:2017
    image: mzz2017/v2raya:latest
    container_name: v2raya
    deploy:
      resources:
        reservations:
          memory: "128M"
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /etc/resolv.conf
        target: /etc/resolv.conf
      - type: bind
        source: /DATA/AppData/$AppID
        target: /etc/v2raya
      - type: bind
        source: /lib/modules
        target: /lib/modules
    x-casaos:
      envs:
        - container: V2RAYA_ADDRESS
          description:
            en_us: v2rayA WebUI Address
            zh_cn: v2rayA WebUI地址
      volumes:
        - container: /etc/v2raya
          description:
            en_us: v2rayA configuration directory
            zh_cn: v2rayA配置目录
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: v2raya
  author: Cp0204
  category: VPN
  description:
    en_us: V2RayA is a web-based V2Ray front-end with enhanced functionality. It provides an intuitive and user-friendly interface to configure and manage your V2Ray server. With V2RayA, you can easily set up and customize your own proxy server with various protocols and encryption methods.
    zh_cn: V2RayA是一个带有增强功能的基于Web的V2Ray前端。它提供了一个直观和用户友好的界面，用于配置和管理V2Ray服务器。使用V2RayA，您可以轻松设置和自定义具有各种协议和加密方法的代理服务器。
  developer: mzz2017
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/v2rayA/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/v2rayA/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/v2rayA/screenshot-2.png
  tagline:
    en_us: Web-based V2Ray front-end
    zh_cn: 基于Web的V2Ray前端
  thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/v2rayA/thumbnail.png
  tips: {}
  title:
    en_us: v2rayA
  index:
  port_map: "2017"
  scheme: http
